import SpaceBackground from "./SpaceBackground";
import "../Experience.css"
const ExperienceCard = ({ position, company, dates, description }) => {
  return (
    <div className="experience-card">
      <div className="experience-header">
        <h3 className="position">{position}</h3>
        <h4 className="company">{company}</h4>
        <p className="dates">{dates}</p>
      </div>
      <div className="experience-description">
        <p>{description}</p>
      </div>
    </div>
  );
};

const Experience = () => (
    <section>
      <SpaceBackground />
      <h2>Experience</h2>
      <div class="experience-section">
      <ExperienceCard 
        position="Software Engineer"
        company="MIDE Technology"
        dates="Jan 2024 - Jul 2024"
        description= "• Streamlined update package firmware for enDAQ CPU and coprocessor that would encrypt a payload generated by an XML schema into EBML and update it over USB. • Automated the build process for five internal projects through Docker containerization and GitHub Actions which resulted in a 35% increase in ticket completion per week. • Developed a scalable internal Python application with a GUI that automated accelerometer signal processing and FFT analysis for testing the accuracy of enDAQ's accelerometer."
      />
      <ExperienceCard 
      position = "Site Reliability Engineer"
      company = "State Street Corp"
      dates = "Jan 2023 - Jul 2023"
      description = "• Developed file-injection testing programs in Azure Chaos Studio to test the resiliency and security of servers managing $4T in global financial transactions from money-laundering hacking exploits. • Programmed adapter in Python that deserializes JSON client requests made to an AI chatbot into an observable dashboard incorporable with Microsoft Teams."
      />
      </div>
    </section>
  );
  
  export default Experience;
  